# Udaya Poudel // 2413993
# Worksheet 1

### Problem 1:

In [29]:
#1. Initialize an empty array with size 2X2.
import numpy as np
e_array=np.empty([2,2])
e_array

array([[4.4e-323, 4.9e-323],
       [5.4e-323, 5.9e-323]])

In [30]:
#2. Initialize an all one array with size 4X2.
o_array=np.ones([4,2])
o_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
fill_array=np.full((2,2),7)
fill_array

array([[7, 7],
       [7, 7]])

In [32]:
#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
fill_zeros_array=np.zeros_like(fill_array)
fill_zeros_array

array([[0, 0],
       [0, 0]])

In [33]:
#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
fill_ones_array=np.ones_like(fill_array)
fill_ones_array

array([[1, 1],
       [1, 1]])

In [34]:
#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list=[1,2,3,4]
new_array=np.array(new_list)
new_array

array([1, 2, 3, 4])

### Problem 2

In [35]:
#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
ranging_array=np.arange(10,49)
ranging_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [36]:
#2. Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}
ranging_array2=np.arange(0,9)
print(f"Before arranging: {ranging_array2}")
reshaped_ranging_array2=ranging_array2.reshape(3,3)
print(f"After arranging: {reshaped_ranging_array2}")

Before arranging: [0 1 2 3 4 5 6 7 8]
After arranging: [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
#3. Create a 3X3 identity matrix.{Hint:np.eye()}
i_matrix=np.eye(3)
i_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
#4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}
randomarray=np.random.random(30)
print(f"Random array: {randomarray}")
print(f"Mean of the array: {randomarray.mean()}")

Random array: [0.07995587 0.67152773 0.49386203 0.79604037 0.79094062 0.04001826
 0.70319878 0.7394137  0.51041301 0.73630126 0.39392613 0.50887448
 0.7742996  0.49529131 0.30800638 0.29213847 0.3979703  0.61422554
 0.00618088 0.10456532 0.03424495 0.68536323 0.81265015 0.57408251
 0.75602948 0.62900885 0.70594501 0.91863435 0.32079791 0.01710555]
Mean of the array: 0.4970337331926557


In [39]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.
random_array2=np.random.random((10,10))
print(f"Random array: {random_array2}")
print(f"Minimum value: {random_array2.min()}")
print(f"Maximum value: {random_array2.max()}")

Random array: [[0.50542862 0.24152702 0.81271383 0.37377289 0.18304546 0.93463452
  0.65498501 0.87469736 0.47348113 0.60523512]
 [0.97895983 0.57532103 0.1100193  0.59864386 0.73833417 0.06189509
  0.35765771 0.71353811 0.92492907 0.02571298]
 [0.67935342 0.58732489 0.63061754 0.98194292 0.20159002 0.39138513
  0.3766582  0.67983021 0.05806656 0.24520666]
 [0.80656303 0.19500769 0.61321307 0.62250783 0.85823403 0.35990922
  0.24236551 0.79007492 0.01644886 0.37605022]
 [0.53286239 0.12162089 0.60891448 0.54652518 0.97308478 0.2903627
  0.40501236 0.9223857  0.36786695 0.02142916]
 [0.97397484 0.49830276 0.05427287 0.5788444  0.88179107 0.7243725
  0.13316639 0.54768108 0.22989215 0.48301306]
 [0.10807909 0.24343848 0.19042574 0.50648544 0.96035507 0.8270863
  0.13210823 0.47582154 0.70423742 0.20986969]
 [0.94298585 0.5683308  0.41054022 0.72972152 0.36319412 0.97732769
  0.50069775 0.70503814 0.17003488 0.12202586]
 [0.89287513 0.72761403 0.17810508 0.45765424 0.05013096 0.86770961
 

In [40]:
#6. Create a zero array of size 10 and replace 5th element with 1.
zarray=np.zeros(10)
print(f"Original Array: {zarray}")
zarray[4]=1
print(f"Modified Array: {zarray}")

Original Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Modified Array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [41]:
#7. Reverse an array arr = [1,2,0,0,4,0].
arr = [1,2,0,0,4,0]
reversedarray=np.flip(arr)
reversedarray

array([0, 4, 0, 0, 2, 1])

In [42]:
#8. Create a 2d array with 1 on border and 0 inside.
original_array=np.ones([3,3])
print(f"Original Array: \n{original_array}")
original_array[1][1]=0
print(f"Modified Array: \n{original_array}")

Original Array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Modified Array: 
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [43]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard_array=np.zeros([8,8])
print(f"Original Array: \n{checkerboard_array}")
checkerboard_array[1::2,::2]=1
checkerboard_array[::2,1::2]=1
print(f"Modified Array: \n{checkerboard_array}")

Original Array: 
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Modified Array: 
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### Problem  3

In [44]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [45]:
#1. Add the two array.
print(f"First output: \n{np.add(x,y)}\n")
print(f"Second output: \n{np.add(v,w)}")

First output: 
[[ 6  8]
 [10 13]]

Second output: 
[20 22]


In [46]:
#2. Subtract the two array.
print(f"First output: \n{np.subtract(x,y)}\n")
print(f"Second output: \n{np.subtract(v,w)}")

First output: 
[[-4 -4]
 [-4 -3]]

Second output: 
[-2 -2]


In [47]:
#3. Multiply the array with any integers of your choice.
print(f"{x*2}\n")
print(f"{y*2}\n")
print(f"{v*2}\n")
print(f"{w*2}\n")

[[ 2  4]
 [ 6 10]]

[[10 12]
 [14 16]]

[18 20]

[22 24]



In [48]:
#4. Find the square of each element of the array.
print(f"{x**2}\n")
print(f"{y**2}\n")
print(f"{v**2}\n")
print(f"{w**2}\n")

[[ 1  4]
 [ 9 25]]

[[25 36]
 [49 64]]

[ 81 100]

[121 144]



In [49]:
#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
print(f"First output: \n{np.dot(v,w)}\n")
print(f"Second output: \n{np.dot(x,v)}\n")
print(f"Third output: \n{np.dot(x,y)}\n")

First output: 
219

Second output: 
[29 77]

Third output: 
[[19 22]
 [50 58]]



In [50]:
#6. Concatenate x(and)y along row and Concatenate v(and)w along column.{Hint:try np.concatenate() or np.vstack() functions.
print(f"First output: \n{np.concatenate((x,y),axis=1)}\n")
print(f"Second output: \n{np.concatenate((v,w),axis=0)}\n")

First output: 
[[1 2 5 6]
 [3 5 7 8]]

Second output: 
[ 9 10 11 12]



In [51]:
#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
print(f"Output: {np.concatenate((x,v),axis=1)}")

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

We get and error while concatenating x and v because they are of different dimensions.

### Problem  4

In [52]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
print(f"A:\n{A} \nB:\n{B}")

A:
[[3 4]
 [7 8]] 
B:
[[5 3]
 [2 1]]


In [53]:
#1. Prove A.A−1 = I.
Ainv=np.linalg.inv(A)
print(f"Ainv:\n{Ainv}")
print(f"A.Ainv:\n{np.dot(A,Ainv)}")

Ainv:
[[-2.    1.  ]
 [ 1.75 -0.75]]
A.Ainv:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [54]:
#2. Prove AB ̸= BA.
print(f"AB:\n{np.dot(A,B)}")
print(f"BA:\n{np.dot(B,A)}")

AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]


In [55]:
#3. Prove (AB)T = BT.AT.
AB=np.dot(A,B)
BT=np.transpose(B)
AT=np.transpose(A)
print(f"(AB)T:\n{np.transpose(AB)}")
print(f"BT.AT:\n{np.dot(BT,AT)}")

(AB)T:
[[23 51]
 [13 29]]
BT.AT:
[[23 51]
 [13 29]]


In [56]:
#• Solve the following system of Linear equation using Inverse Methods.
#2x − 3y + z = −1
#x − y + 2z = −3
#3x + y − z = 9
A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B=np.array([-1,-3,9])
AI=np.linalg.inv(A)
X=np.dot(AI,B)
print(f"x={X[0]}\ny={X[1]}\nz={X[2]}")

x=2.0
y=1.0000000000000002
z=-1.9999999999999996


### TEST How Fast is Numpy?

#### 1. Element-wise Addition

In [57]:
import random
from timeit import timeit
def add_python(Z1,Z2):
  return [z1+z2 for z1,z2 in zip(Z1,Z2)]
def add_numpy(Z1,Z2):
  return np.add(Z1,Z2)
size=1000000
Z1_list=random.sample(range(size+1),size)
Z2_list=random.sample(range(size+1),size)
Z1_np=np.array(Z1_list)
Z2_np=np.array(Z2_list)
python_time=timeit("add_python(Z1_list,Z2_list)",number=1,globals=globals())
numpy_time=timeit("add_numpy(Z1_np,Z2_np)",number=1,globals=globals())
print("Python Time:",python_time)
print("Numpy Time:",numpy_time)

Python Time: 0.21200430199999687
Numpy Time: 0.0014837829999976293


#### 2. Element-wise Multiplication

In [58]:
def mul_python(Z1,Z2):
  return [z1*z2 for z1,z2 in zip(Z1,Z2)]
def mul_numpy(Z1,Z2):
  return np.multiply(Z1,Z2)
size=1000000
Z1_list=random.sample(range(size+1),size)
Z2_list=random.sample(range(size+1),size)
Z1_np=np.array(Z1_list)
Z2_np=np.array(Z2_list)
python_time=timeit("mul_python(Z1_list,Z2_list)",number=1,globals=globals())
numpy_time=timeit("mul_numpy(Z1_np,Z2_np)",number=1,globals=globals())
print("Python Time:",python_time)
print("Numpy Time:",numpy_time)

Python Time: 0.21689529100001437
Numpy Time: 0.0024992589999897064


#### 3. Dot product

In [59]:
def dot_python(Z1,Z2):
  return sum(z1*z2 for z1,z2 in zip(Z1,Z2))
def dot_numpy(Z1,Z2):
  return np.dot(Z1,Z2)
size=1000000
Z1_list=random.sample(range(size+1),size)
Z2_list=random.sample(range(size+1),size)
Z1_np=np.array(Z1_list)
Z2_np=np.array(Z2_list)
python_time=timeit("dot_python(Z1_list,Z2_list)",number=1,globals=globals())
numpy_time=timeit("dot_numpy(Z1_np,Z2_np)",number=1,globals=globals())
print("Python Time:",python_time)
print("Numpy Time:",numpy_time)

Python Time: 0.23568667600000026
Numpy Time: 0.0010032430000137538


#### 4. Matrix Multiplication

In [60]:
size=1000
Z1_list = [random.sample(range(size),size) for _ in range(size)]
Z2_list = [random.sample(range(size),size) for _ in range(size)]
Z1_np = np.array(Z1_list)
Z2_np = np.array(Z2_list)
def np_matmul(Z1,Z2):
  return np.matmul(Z1,Z2)
def python_matmul(Z1,Z2):
  return [[sum(z1*z2 for z1,z2 in zip(Z1_row,Z2_col)) for Z2_col in zip(*Z2)] for Z1_row in Z1]
python_time=timeit("python_matmul(Z1_list,Z2_list)",number=1,globals=globals())
numpy_time=timeit("np_matmul(Z1_np,Z2_np)",number=1,globals=globals())
print("Python Time:",python_time)
print("Numpy Time:",numpy_time)

Python Time: 169.552809846
Numpy Time: 2.1558195259999593


## Practice Questions

In [61]:
import numpy as np
# initialize an all zero array with size 2 X 3:
zeros_arr = np . zeros ((2 ,3) )
print (" A zeros array is \n", zeros_arr , " with dimensions ", zeros_arr . shape , "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]]  with dimensions  (2, 3) 



In [73]:
import numpy as np
# Create and display zero , one , and n- dimensional arrays
zero_dim_array = np . array (5)
one_dim_array = np . array ([1 , 2 , 3])
n_dim_array = np . array ([[1 , 2] , [3 , 4]])
for arr in [ zero_dim_array , one_dim_array , n_dim_array ]:
  print ( f" Array :\n{arr }\nDimension : {arr. ndim }\nData type :{arr. dtype }\n")

 Array :
5
Dimension : 0
Data type :int64

 Array :
[1 2 3]
Dimension : 1
Data type :int64

 Array :
[[1 2]
 [3 4]]
Dimension : 2
Data type :int64



In [74]:
import numpy as np
array = np . array ([[1 , 2 , 3] , [4 , 5 , 6]]) # Shape (2 , 3)
reshaped_array = array . reshape (3 , 2) # Reshape to (3 ,2) , keeping 6 elements
print (" Original Shape :", array . shape , "\nReshaped Shape :", reshaped_array . shape )

 Original Shape : (2, 3) 
Reshaped Shape : (3, 2)


In [64]:
import numpy as np
a = np . arange (1 , 10)
print ( a )
x = range (1 , 10)
print ( x ) # x is an iterator
print ( list ( x ) )
# further arange examples :
x = np . arange (10.4)
print ( x )
x = np . arange (0.5 , 10.4 , 0.8)
print ( x )

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [65]:
import numpy as np
# 50 values between 1 and 10:
print ( np . linspace (1 , 10) )
# 7 values between 1 and 10:
print ( np . linspace (1 , 10 , 7) )
# excluding the endpoint :
print ( np . linspace (1 , 10 , 7 , endpoint = False ) )

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [66]:
import numpy as np
arr1 = np . array ([[1 , 2] , [3 , 4]]) # Shape : (2 , 2)
arr2 = np . array ([[5 , 6] , [7 , 8]]) # Shape : (2 , 2)
# Stacking examples
hstacked = np . hstack (( arr1 , arr2 ) )
# Output hstack : [[1 2 5 6] [3 4 7 8]]
vstacked = np . vstack (( arr1 , arr2 ) )
# Output vstack [[1 2] [3 4] [5 6] [7 8]]
colstacked = np . column_stack (( arr1 [0] , arr2 [0]) )
# Output column stack : [[1 5] [2 6]]
print ( hstacked , vstacked , colstacked , sep ='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


In [67]:
import numpy as np
arr1 = np . array ([[1 , 2] , [3 , 4]]) # Shape : (2 , 2)
arr2 = np . array ([[5 , 6] , [7 , 8]]) # Shape : (2 , 2)
concat_axis0 = np . concatenate (( arr1 , arr2 ) , axis =0)
# Concatenate along axis 0 ( vertical ) Shape : (4 , 2)
concat_axis1 = np . concatenate (( arr1 , arr2 ) , axis =1)
# Concatenate along axis 1 ( horizontal ) Shape : (2 , 4)
print ( concat_axis0 , concat_axis1 , sep ='\n')

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## Slicing and Indexing

In [68]:
import numpy as np
# Arrays
arr1d = np . array ([0 , 1 , 2 , 3 , 4 , 5])
arr2d = np . array ([[0 , 1 , 2] , [3 , 4 , 5] , [6 , 7 , 8]])
arr3d = np . array ([[[0 , 1] , [2 , 3]] , [[4 , 5] , [6 , 7]] , [[8 ,9] , [10 , 11]]])
# Slicing examples
print (" Basic :", arr1d [1:4] , arr2d [1:3 , 0:2] , arr3d [1:2 , 0:2 ,1:2])
# Output Basic : arr1d :[1 2 3] arr2d :[[3 4] [6 7]] arr3d:[[[5] [7]]]
print (" Step :", arr1d [1:5:2] , arr2d [::2 , 1::2] , arr3d [::2 ,::2 , 1::2])
# Output : Step : [1 3] [[1] [7]] [[[1] [9]]]

 Basic : [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
 Step : [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


## Array Mathematics

In [69]:
import numpy as np
arr1 = np . array ([1 , 2 , 3])
arr2 = np . array ([4 , 5 , 6])
print ("Add:", np . add ( arr1 , arr2 ) ) # Output Add: [5 7 9]
print (" Subtract :", np . subtract ( arr1 , arr2 ) )
# Output Subtract : [ -3 -3 -3]
print (" Divide :", np . divide ( arr1 , arr2 ) )
# Output Divide : [0.25 0.4 0.5 ]
print (" Multiply :", np . multiply ( arr1 , arr2 ) )
# Output Multiply : [ 4 10 18]
print (" Power :", np . power ( arr1 , arr2 ) )
# Output Power : [ 1 32 729]
print ("Exp:", np . exp ( arr1 ) )
# Output Exp: [ 2.71828183 7.3890561 20.08553692]

Add: [5 7 9]
 Subtract : [-3 -3 -3]
 Divide : [0.25 0.4  0.5 ]
 Multiply : [ 4 10 18]
 Power : [  1  32 729]
Exp: [ 2.71828183  7.3890561  20.08553692]


## Matrix Multiplications

In [70]:
import numpy as np
# Define two matrices
A = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
B = np . array ([[7 , 8] , [9 , 10] , [11 , 12]])
# Matrix multiplication using np.dot
result_dot = np . dot (A , B )
print (" Result with np.dot :\n", result_dot ) # Output shape :(2 , 2)

 Result with np.dot :
 [[ 58  64]
 [139 154]]


In [71]:
import numpy as np
# Define two matrices
A = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
B = np . array ([[7 , 8] , [9 , 10] , [11 , 12]])
# Matrix multiplication using @ operator
result_at = A @ B
print (" Result with @ operator :\n", result_at ) # Outputshape : (2 , 2)
# Matrix multiplication using np. matmul
result_matmul = np . matmul (A , B )
print (" Result with np. matmul :\n", result_matmul ) # Outputshape : (2 , 2)

 Result with @ operator :
 [[ 58  64]
 [139 154]]
 Result with np. matmul :
 [[ 58  64]
 [139 154]]


## Linear Algebra with Numpy

In [72]:
import numpy as np
A = np . array ([[1 , 2] , [3 , 4]])
B = np . array ([5 , 6])
print (" Inverse :\n", np . linalg . inv ( A ) )
# Output : Inverse : [[ -2. 1. ] , [ 1.5 -0.5]]
print (" Determinant :", np . linalg . det ( A ) )
# Output : Determinant : -2.0
print (" Frobenius Norm :", np . linalg . norm (A , 'fro') )
# Output : Frobenius Norm : 5.4772
print ("2 - Norm ( Euclidean ):", np . linalg . norm ( A ) )
# Outptut : 2 - Norm ( Euclidean ): 5.4772
print (" Solution x:", np . linalg . solve (A , B ) )
# Output : Solution x: [ -4. 4.5]

 Inverse :
 [[-2.   1. ]
 [ 1.5 -0.5]]
 Determinant : -2.0000000000000004
 Frobenius Norm : 5.477225575051661
2 - Norm ( Euclidean ): 5.477225575051661
 Solution x: [-4.   4.5]
